name: Generate Shadowrocket Rules

on:
  schedule:
    - cron: '0 1 * * *' # 每天凌晨 1 点 UTC (台北时间上午 9 点)
  workflow_dispatch: # 手动触发工作流程

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run script
        run: python convert_rules.py

      - name: Configure Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Get file SHA (or empty if it doesn't exist)
        id: get_sha
        run: |
          SHA=$(git ls-tree -z HEAD sbautorule.json | cut -d ' ' -f 3 2>/dev/null) # Suppress error if file doesn't exist
          echo "::set-output name=sha::$SHA"

      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('./sbautorule.json', 'utf8');
            const sha = '${{ steps.get_sha.outputs.sha }}';

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'sbautorule.json',
              message: 'Update Shadowrocket rules',
              content: Buffer.from(content).toString('base64'),
              sha: sha === '' ? undefined : sha, // Use undefined if SHA is empty
              committer: {
                name: 'GitHub Actions Bot',
                email: 'actions@github.com'
              }
            });

      - name: Clear cache (optional)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
