name: Generate Shadowrocket Rules

on:
  schedule:
    - cron: '0 1 * * *' # 每天凌晨 1 点 UTC (台北时间上午 9 点)
  workflow_dispatch: # 手动触发工作流程

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run script
        run: python convert_rules.py

      - name: Configure Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Remove sbautorule.json if it exists (for scheduled runs)
        if: github.event_name == 'schedule'
        run: |
          if [[ -f sbautorule.json ]]; then
            rm sbautorule.json
            git rm sbautorule.json
            git commit -m "Remove sbautorule.json (Scheduled)"
            git push origin main # 指定 origin 仓库的 main 分支
          fi

      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = './sbautorule.json';

            if (!fs.existsSync(path)) {
              fs.writeFileSync(path, '{}');
            }

            const content = fs.readFileSync(path, 'utf8');
            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'sbautorule.json',
              message: 'Update Shadowrocket rules',
              content: Buffer.from(content).toString('base64'),
              sha: undefined,
              committer: {
                name: 'GitHub Actions Bot',
                email: 'actions@github.com'
              }
            });

      - name: Clear cache (optional)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
