name: Generate Shadowrocket Rules

on:
  schedule:
    - cron: '0 1 * * *' # 每天凌晨 1 點 UTC (台北時間上午 9 點)
  workflow_dispatch: # 手動觸發工作流程

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run script
        run: python convert_rules.py

      - name: Get latest SHA
        id: get_sha
        run: |
          sha=$(git ls-tree -z HEAD sbrule.conf | cut -d ' ' -f 3)
          echo "::set-output name=sha::$sha"

      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('./sbrule.conf', 'utf8');
            const sha = '${{ steps.get_sha.outputs.sha }}'; // 使用最新的 SHA
            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'sbrule.conf',
              message: 'Update Shadowrocket rules',
              content: Buffer.from(content).toString('base64'),
              sha: sha  // 使用最新的 SHA
            });
