name: Generate Shadowrocket Rules

on:
  workflow_dispatch: # 手動觸發工作流程 (移除 schedule)

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run script
        run: python convert_rules.py

      - name: Get file SHA or create if it doesn't exist
        id: get_sha
        shell: bash
        run: |
          if [[ -f sbrule.conf ]]; then
            sha=$(git ls-tree -z HEAD sbrule.conf | cut -d ' ' -f 3)
            echo "sha=$sha" >> $GITHUB_OUTPUT
          else
            echo "sha=" >> $GITHUB_OUTPUT # 如果檔案不存在，sha 設定為空字串
          fi

      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('./sbrule.conf', 'utf8');
            const sha = '${{ steps.get_sha.outputs.sha }}';
            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'sbrule.conf',
              message: 'Update Shadowrocket rules',
              content: Buffer.from(content).toString('base64'),
              sha: sha === '' ? undefined : sha // 處理檔案建立的情況
            });

      # 清除相關快取 (可選，如果問題仍然存在)
      - name: Clear cache (optional)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip # 清除 pip 快取
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }} # 使用 requirements.txt 檔案雜湊作為快取鍵
          restore-keys: |
            ${{ runner.os }}-pip-
