name: Generate Sing-box Rules

on:
  workflow_dispatch:  # 手動觸發工作流程

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run script
        run: python extract_and_convert.py

      - name: Rename output file
        run: mv singbox_rules.yaml sbrule.conf  # 將 singbox_rules.yaml 重命名為 sbrule.conf

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update Shadowrocket rules'
          file_pattern: sbrule.conf
