name: Generate Shadowrocket Rules

on:
  schedule:
    - cron: '0 1 * * *' # 每天凌晨 1 點 UTC (台北時間上午 9 點)
  workflow_dispatch: # 手動觸發工作流程

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run script
        run: python convert_rules.py

      - name: Get file SHA or create if it doesn't exist
        id: get_sha
        shell: bash
        run: |
          if [[ -f sbautorule.json ]]; then # 檔案名更改為 sbautorule.json
            sha=$(git ls-tree -z HEAD sbautorule.json | cut -d ' ' -f 3) # 檔案名更改為 sbautorule.json
            echo "sha=$sha" >> $GITHUB_OUTPUT
          else
            echo "sha=" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('./sbautorule.json', 'utf8'); # 檔案名更改為 sbautorule.json
            const sha = '${{ steps.get_sha.outputs.sha }}';
            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'sbautorule.json', # 檔案名更改為 sbautorule.json
              message: 'Update Shadowrocket rules',
              content: Buffer.from(content).toString('base64'),
              sha: sha === '' ? undefined : sha // 處理檔案建立的情況
            });

      # 清除相關快取 (可選，如果問題仍然存在)
      - name: Clear cache (optional)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
